package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/DISCARDING.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Friday, February 3, 2012 8:32:08 PM PST
*/

public interface DISCARDING
{

  /** Object adapter state that causes all requests to be discarded.
   */
  public static final short value = (short)(2);
}
